//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifyMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kindergartenNetwork.Resources.NotifyMsg", typeof(NotifyMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التفعيل بنجاح.
        /// </summary>
        public static string ActiveSuccessMsg {
            get {
                return ResourceManager.GetString("ActiveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد؟.
        /// </summary>
        public static string ConfermationMinMsg {
            get {
                return ResourceManager.GetString("ConfermationMinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danger.
        /// </summary>
        public static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        public static string DeleteSuccessMsg {
            get {
                return ResourceManager.GetString("DeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور خاطئة.
        /// </summary>
        public static string ErrorIncorrect {
            get {
                return ResourceManager.GetString("ErrorIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الحقل.
        /// </summary>
        public static string ErrorInField {
            get {
                return ResourceManager.GetString("ErrorInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملية فشلت.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded the allowable number of times.
        /// </summary>
        public static string ErrorPass {
            get {
                return ResourceManager.GetString("ErrorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الاضافة بنجاح.
        /// </summary>
        public static string InsertSuccessMsg {
            get {
                return ResourceManager.GetString("InsertSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتحقق بعض الشروط.
        /// </summary>
        public static string NotValidCodations {
            get {
                return ResourceManager.GetString("NotValidCodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك بعض الاخطاء , اصلحها ثم حاول مرة أخرى.
        /// </summary>
        public static string NotValidMsg {
            get {
                return ResourceManager.GetString("NotValidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحفظ بنجاح.
        /// </summary>
        public static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتملت العملية بنجاح.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية تحديث البيانات بنجاح.
        /// </summary>
        public static string UpdateSuccessMsg {
            get {
                return ResourceManager.GetString("UpdateSuccessMsg", resourceCulture);
            }
        }
    }
}
